### PR TITLE
Run `submitIO` in a bound thread

### LINKED ISSUE #58: GHC `ghc_worker` thread exits interact badly with io_uring's buffered-read fallback path
> Disclaimer: this was put together with Claude's help. I have read the text and I think everything said on it is accurate.

Follow-up from https://github.com/IntersectMBO/lsm-tree/issues/839

## Context

Running cardano-node on a Raspberry Pi 5 (8 GB RAM, NVMe drive, 2 GB swap, kernel 6.17.0, arm64) with the UTxO-HD / lsm-tree backend. Around slot 50M and under sustained memory pressure (~4 GB RSS), the node crashes repeatedly with `EFAULT` (errno -14) during io_uring reads of `.keyops` files.

## Identified cause

cardano-node on static-musl arm64 crashes with `EFAULT` (errno -14) from io_uring **buffered** reads because:

1. GHC's threaded RTS maintains a pool of worker OS threads (`ghc_worker`) for safe FFI calls and bound-thread work.
2. These worker threads are **short-lived** -- they exit when idle, causing continuous churn (we measured ~50-60 `ghc_worker` exits every 30 seconds while the node is running).
3. `io_uring` buffered read operations (the default `DiskCacheAll` policy in lsm-tree) use `task_work` to deliver the completion of reads that had to fetch pages from disk. `task_work` is delivered back into the submitting `task_struct`'s context.
4. When the submitter thread exits before the block I/O completes, `task_work_add` fails with `-ESRCH` and the request is deferred to the kernel workqueue via `ctx->fallback_llist` / `io_fallback_req_func`.
5. In that fallback context, `io_req_task_submit` checks `req->task->flags & PF_EXITING` and, finding it set, calls `io_req_defer_failed(req, -EFAULT)` -- producing our errno -14.

The buffer is fine. The file descriptor is fine. The data is fine.  The kernel rejects the operation solely because the submitting OS thread was being torn down when the read callback tried to deliver back to it.

**This bug is specific to BUFFERED reads via io_uring.** O_DIRECT reads submit their DMA synchronously inside `io_uring_enter` and don't use `task_work` for completion, so they are not affected.

## Kernel-side evidence

Captured with bpftrace by hooking two kernel probes on the running cardano-node process (kernel 6.17, arm64):

1. tracepoint:io_uring:io_uring_complete filtered on args->res < 0 -- shows every io_uring request that completed with an error.
2. kprobe:io_req_defer_failed -- fires whenever the io_uring fallback path deliberately completes a request with a kernel-chosen errno.

One-shot script:

```
kprobe:io_req_defer_failed /(int32)arg1 == -14/
{
  printf("[%ld.%06ld] io_req_defer_failed(-EFAULT) running-in=%s tid=%d\n",
         elapsed / 1000000000, (elapsed % 1000000000) / 1000,
         comm, tid);
  printf("  stack:%s\n---\n", kstack(15));
}
```

Captured during a live crash:

```
[424.616672] io_req_defer_failed(-EFAULT) running-in=kworker/1:2 tid=116195
    stack:
          io_req_defer_failed+0
          io_fallback_req_func+128
          process_one_work+344
          worker_thread+392
          kthread+280
          ret_from_fork+16
```

`comm=kworker/1:2` (a generic kernel workqueue worker, not an `iou-wrk-*` io_uring worker nor the submitter process) plus the stack bottoming out in `io_fallback_req_func` shows this is the io_uring fallback workqueue path -- triggered when a previous `task_work_add(req->task, ...)` failed because the submitting task has exited. The `-EFAULT` comes from the unconditional `io_req_defer_failed(req, -EFAULT)` in `io_req_task_submit` for requests whose owning task is in `PF_EXITING` (or already gone). The userspace-visible `Errno -14` in the CQE is stamped by the kernel there, not derived from a bad buffer address.

## The liburing code

In `io_uring/io_uring.c`:

```c
static __cold void io_fallback_req_func(struct work_struct *work)
{
    struct io_ring_ctx *ctx = container_of(work, struct io_ring_ctx,
                                           fallback_work.work);
    struct llist_node *node = llist_del_all(&ctx->fallback_llist);
    struct io_kiocb *req, *tmp;
    struct io_tw_state ts = {};

    mutex_lock(&ctx->uring_lock);
    llist_for_each_entry_safe(req, tmp, node, io_task_work.node)
        req->io_task_work.func(req, ts);      // --> io_req_task_submit
    io_submit_flush_completions(ctx);          // --> tracepoint fires
    mutex_unlock(&ctx->uring_lock);
}
```

And `io_req_task_submit` contains the EFAULT-producing branch:

```c
void io_req_task_submit(struct io_kiocb *req, struct io_tw_state *ts)
{
    io_tw_lock(req->ctx, ts);
    if (unlikely(req->task->flags & PF_EXITING))
        io_req_defer_failed(req, -EFAULT);       // <-- here
    ...
}
```

`PF_EXITING` is set on the `task_struct` when the task is in the process
of exiting (between `do_exit()` entry and final cleanup).

## Why the GHC runtime hits this

GHC's threaded runtime maintains a pool of short-lived OS threads (named `ghc_worker`) that back **safe FFI** calls and bound-thread work. A Haskell green thread that enters a `safe` foreign call is handed off to a worker OS thread for the duration of the call, and then — crucially — **continues running on that worker** until its next scheduler yield  point. When the green thread later yields (e.g. blocks on an `MVar`), the worker is released; if no new work arrives promptly, the RTS reaps it and it exits.

`blockio-uring` performs its `io_uring_enter` syscall via an `unsafe` FFI call inside `submitIO`. Because unsafe FFI runs on whichever OS thread is currently carrying the green thread, this syscall can end up being issued by a transient `ghc_worker`. The kernel stores that worker's `task_struct` as `req->task`. `submitIO` then blocks on the completion `MVar`, yielding the green thread off the worker — the worker is now idle and eligible for reaping.

Measured on the crashing cardano-node via `tracepoint:sched:sched_process_exit`:

```
@exits[ghc_worker]: ~50-60 exits every 30 seconds (sustained)
```

So at any moment there are dozens of recently-issued io_uring requests whose recorded submitter task is already gone. When a buffered read among them finishes its disk I/O, the kernel's bio completion callback (`io_async_buf_func`) tries `task_work_add(req->task, …)`, gets `-ESRCH`, pushes the request onto `ctx->fallback_llist`, and the workqueue path stamps `-EFAULT` on the CQE.

The fix is to ensure the `io_uring_enter` syscall is always issued from a long-lived OS thread whose lifetime covers the async window — either by funnelling all submissions through a dedicated bound thread (`forkOS`) per ring, or by wrapping `submitCapIO` in `runInBoundThread` so the submitter stays alive until its completions are delivered.

## Prior art in other io_uring ecosystems

This isn't a new class of problem — other async runtimes built on io_uring ran into the same task-affinity constraint and designed around it. We didn't find a prior bug report with our exact `-EFAULT`-from-fallback symptom, but the underlying design principle ("the submitter's task identity is load-bearing; runtimes that can't guarantee a stable long-lived submitter will have correctness problems") is well established.

- **[tokio-uring DESIGN.md](https://github.com/tokio-rs/tokio-uring/blob/master/DESIGN.md)** — Rust's main io_uring runtime. Runs one io_uring instance per thread in a **thread-per-core** model, makes operation futures and buffers **`!Send`** so the type system forbids migrating in-flight operations across threads. They explicitly cite problems this prevents (fd reuse races, cancellation races, buffer-lifetime races); our bug is another flavor of the same class. `blockio-uring`'s current design — any Haskell thread may be the submitter — is structurally what tokio-uring's authors chose *against*.

- **[Apache Iggy: thread-per-core io_uring migration (Feb 2026)](https://iggy.apache.org/blogs/2026/02/27/thread-per-core-io_uring/)** — The Iggy message broker moved off the default Tokio runtime onto a thread-per-core architecture because Tokio's blocking thread pool for file I/O (the direct analog of GHC's `ghc_worker` pool) didn't scale under load. Different symptom, same underlying diagnosis: dynamic pools of short-lived OS threads don't compose well with io_uring.

- **[IORING_SETUP_SINGLE_ISSUER / IORING_SETUP_DEFER_TASKRUN (LWN)](https://lwn.net/Articles/906470/)** — Kernel-side acknowledgement: io_uring itself added setup flags that *require* a single, long-lived submitter task. Their existence is an admission by the kernel authors that the submitter's task identity is load-bearing; runtimes that can't make that guarantee are operating in a mode that gives up some correctness and performance.

- **[liburing issue #109: "submit requests from any thread"](https://github.com/axboe/liburing/issues/109)** — Closed as won't do. A long-standing request for io_uring to relax its single-issuer assumption. Still unresolved, confirming that the task-bound property is fundamental to current io_uring rather than an implementation detail that will be fixed soon.

- **[io_uring_enter(2) man page](https://man7.org/linux/man-pages/man2/io_uring_enter.2.html)** — Documents, in adjacent contexts, that "the submitting thread can be invalid" is a real failure mode. Our failure path is different (buffered-read fallback, not `IORING_ENTER_GETEVENTS` with `DEFER_TASKRUN`), but in the same spirit.

## Workaround

The PR https://github.com/well-typed/blockio-uring/pull/59 shows a minimal workaround that lets the cardano-node run without crashing due to this problem.

This fix was deployed in the last restart on this graph (the one all to the right side) and shows a clear different pattern than the previous part of the graph where the node crashed in 10-15 minutes intervals, this time running for 1h15m uninterrupted.

Image

### PR DESCRIPTION
**Pull request by jorisdral**
Resolves #58

### CODE REVIEW

File: src/System/IO/BlockIO.hs [hunk 1]
```diff
@@ -296,16 +296,23 @@ data IOOp s = IOOpRead  !Fd !FileOffset !(MutableByteArray s) !Int !ByteCount
...
-    submitCapIO capctx ioops
+submitIO (IOCtx capctxs) !ioops =
+    -- Requests have to be submitted from within a bound thread, or we might get
+    -- @EFAULT@ errors. See issue #58.
+    --
+    -- TODO <>: ideally, for performance, it would be better to run a smaller
+    -- section of the 'submitIO' code inside 'runInBoundThread'. However, it is
+    -- not 100% clear what the critical code section is that /has/ to run in a
+    -- bound thread . So, for now we pick the safe option of running the
+    -- entirety of 'submitIO' in a bound thread.
```
Comment (jorisdral) [inline src/System/IO/BlockIO.hs]: Right, so  ideally, for performance, it would be better to run a smaller section of the `submitIO` code inside `runInBoundThread`. However, it is not 100% clear what the critical code section is that has to run in a bound thread, that would require some more investigation.

We went with the safe option of running the entirety of `submitIO` in a bound thread for now, but before I made  that decision I decided to run some benchmarks for `lsm-tree` with the changes in this PR to see if it has a detrimental effect on performance. It looked like it made no real difference, though it is likely that performance decreases with the amount of available CPU/memory resources on a system. The system I ran the benchmarks on is not so constrained.

**Comment by dcoutts** [comment]
I don't believe this.

Given that the hypothesis from issue #58 is that the task must still be live by the time the IO _completes_, then using some arbitrary bound thread for just the submission part is not a solution. It may work but what is the theory that explains why it is correct?

File: src/System/IO/BlockIO.hs (hunk 1 above)
Comment (dcoutts) [reply src/System/IO/BlockIO.hs]: What is the theory / explanation for why running the submission in a bound thread solves the problem? It doesn't seem to be related to the theory of the case in #58.

**Comment by jorisdral** [comment]
See https://github.com/well-typed/blockio-uring/issues/58#issuecomment-4642433007

**Comment by dcoutts** [comment]
Yes ok. I misread it. https://github.com/well-typed/blockio-uring/issues/58#issuecomment-4642753699
